"use client";

import { useState } from "react";
import { ConsentGate } from "../../components/ConsentGate";
import { Funnel } from "../../components/Funnel";
import type { ResultSchema } from "../../lib/api-types";

const initial = "We need a backend engineer with Python, SQL, Docker and AWS experience. The role is based in Bengaluru.";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function Screen() {
  const [jd, setJd] = useState(initial); const [schema, setSchema] = useState<ResultSchema>(); const [jobId, setJobId] = useState<number>(); const [agentId, setAgentId] = useState<number>(); const [language, setLanguage] = useState("ENGLISH"); const [candidateName, setCandidateName] = useState(""); const [phone, setPhone] = useState(""); const [consentProof, setConsentProof] = useState(""); const [contactId, setContactId] = useState<number>(); const [message, setMessage] = useState("");
  async function derive() { const response = await fetch(`${api}/jobs/screen`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jd }) }); if (!response.ok) return setMessage("Could not derive the review schema. Check that the backend is running."); const data = await response.json(); setSchema(data.result_schema); setJobId(data.id); setMessage("Review the extraction below before provisioning an agent."); }
  async function provision() { if (!schema || !jobId) return; const response = await fetch(`${api}/agents/provision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ job_id: jobId, name: "Screening agent", result_schema: schema, language }) }); if (!response.ok) return setMessage("Provisioning failed. Confirm that the backend has a valid Hunar key."); const data = await response.json(); setAgentId(data.id); setMessage("Agent provisioned. Add a consented candidate below."); }
  async function addAndVerifyCandidate() { const created = await fetch(`${api}/contacts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: candidateName, phone, source: "manual" }) }); if (!created.ok) return setMessage("Could not save the candidate."); const contact = await created.json(); const verified = await fetch(`${api}/contacts/${contact.id}/verify`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ consent_proof: consentProof }) }); if (!verified.ok) return setMessage("A consent proof is required before this number can be dialled."); setContactId(contact.id); setMessage("Candidate verified. The number is now eligible for a consented call."); }
  async function dispatch() { if (!contactId || !agentId) return; const response = await fetch(`${api}/dispatch/${contactId}/${agentId}`, { method: "POST" }); setMessage(response.ok ? "Call queued. Outcomes will appear in Proof as webhooks arrive." : "Dispatch failed. Check the provider key and deployment configuration."); }
  return <main><p className="eyebrow">Screen · Q1</p><h1>Turn a job description into a reviewable voice screen.</h1><p className="lede">The operator approves the criteria and prompt before any candidate is contacted.</p><section className="panel"><label htmlFor="jd">Job description</label><textarea id="jd" rows={9} value={jd} onChange={event => setJd(event.target.value)} /><button onClick={derive}>Derive screening schema</button>{message && <p className="status ok">{message}</p>}</section>{schema && <section className="panel"><h2>Approval boundary: result schema</h2><table><tbody>{Object.entries(schema).map(([key, value]) => <tr key={key}><th>{key}</th><td>{value}</td></tr>)}</tbody></table><label>Language</label><select value={language} onChange={event => setLanguage(event.target.value)}><option value="ENGLISH">English</option><option value="HINDI">Hindi</option><option value="TAMIL">Tamil</option></select><button onClick={provision}>Approve and provision agent</button></section>}<ConsentGate />{agentId && <section className="panel"><h2>Add a consented candidate</h2><label>Name</label><input value={candidateName} onChange={event => setCandidateName(event.target.value)} /><label>Verified phone</label><input value={phone} onChange={event => setPhone(event.target.value)} placeholder="+919999999999" /><label>Consent proof</label><input value={consentProof} onChange={event => setConsentProof(event.target.value)} placeholder="Source and timestamp of recorded consent" /><button onClick={addAndVerifyCandidate}>Record consent</button>{contactId && <button onClick={dispatch}>Dispatch consented call</button>}</section>}<Funnel /></main>;
}
